version: '3.7'
services:
  apcupsd2mqtt:
    build:
      context: .
      dockerfile: Dockerfile
    image: apcupsd2mqtt
    container_name: apcupsd2mqtt
    restart: unless-stopped
    volumes:
      - ./etc/apcupsd:/etc/apcupsd:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/New_York
      - DEBUG=true
    network_mode: host
    devices:
      - /dev/usb/hiddev0:/dev/usb/hiddev0
    privileged: true

